import { addDays, addHours, startOfDay } from 'date-fns';

// Helper function to generate dates
const today = startOfDay(new Date());
const tomorrow = addDays(today, 1);
const nextWeek = addDays(today, 7);

// Generate more realistic date ranges that will be visible
const yesterday = addDays(today, -1);
const twoDaysAgo = addDays(today, -2);
const threeDaysFromNow = addDays(today, 3);
const fiveDaysFromNow = addDays(today, 5);

export function getDummyData() {
    // Cast everything as any to avoid type issues for now
    const workCells = [
        {
            id: 1,
            name: 'CNC Machine 1',
            description: 'High precision CNC machining center',
            cell_type: 'internal',
            has_finite_capacity: true,
            default_production_rate_per_hour: 10,
            default_unit_of_measure: 'units',
            default_setup_time_minutes: 30,
            max_parallel_executions: 1,
            is_active: true,
            area_id: 1,
            area: {
                id: 1,
                name: 'Machining Area',
                description: 'Main machining area',
                plant_id: 1,
                plant: {
                    id: 1,
                    name: 'Main Plant',
                    description: 'Main manufacturing facility',
                    address: '123 Industrial Ave',
                    created_at: '2024-01-01T00:00:00Z',
                    updated_at: '2024-01-01T00:00:00Z',
                },
                created_at: '2024-01-01T00:00:00Z',
                updated_at: '2024-01-01T00:00:00Z',
            },
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
        },
        {
            id: 2,
            name: 'Assembly Station A',
            description: 'Manual assembly workstation',
            cell_type: 'internal',
            has_finite_capacity: true,
            default_production_rate_per_hour: 20,
            default_unit_of_measure: 'units',
            default_setup_time_minutes: 15,
            max_parallel_executions: 2,
            is_active: true,
            area_id: 2,
            area: {
                id: 2,
                name: 'Assembly Area',
                description: 'Main assembly area',
                plant_id: 1,
                plant: {
                    id: 1,
                    name: 'Main Plant',
                    description: 'Main manufacturing facility',
                    address: '123 Industrial Ave',
                    created_at: '2024-01-01T00:00:00Z',
                    updated_at: '2024-01-01T00:00:00Z',
                },
                created_at: '2024-01-01T00:00:00Z',
                updated_at: '2024-01-01T00:00:00Z',
            },
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
        },
        {
            id: 3,
            name: 'Welding Bay 1',
            description: 'Robotic welding station',
            cell_type: 'internal',
            has_finite_capacity: true,
            default_production_rate_per_hour: 15,
            default_unit_of_measure: 'units',
            default_setup_time_minutes: 45,
            max_parallel_executions: 1,
            is_active: true,
            area_id: 3,
            area: {
                id: 3,
                name: 'Welding Area',
                description: 'Welding and joining area',
                plant_id: 1,
                plant: {
                    id: 1,
                    name: 'Main Plant',
                    description: 'Main manufacturing facility',
                    address: '123 Industrial Ave',
                    created_at: '2024-01-01T00:00:00Z',
                    updated_at: '2024-01-01T00:00:00Z',
                },
                created_at: '2024-01-01T00:00:00Z',
                updated_at: '2024-01-01T00:00:00Z',
            },
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
        },
        {
            id: 4,
            name: 'Quality Control Station',
            description: 'Quality inspection and testing',
            cell_type: 'internal',
            has_finite_capacity: false,
            default_production_rate_per_hour: 30,
            default_unit_of_measure: 'units',
            default_setup_time_minutes: 10,
            max_parallel_executions: 3,
            is_active: true,
            area_id: 4,
            area: {
                id: 4,
                name: 'Quality Control',
                description: 'Quality control and inspection area',
                plant_id: 1,
                plant: {
                    id: 1,
                    name: 'Main Plant',
                    description: 'Main manufacturing facility',
                    address: '123 Industrial Ave',
                    created_at: '2024-01-01T00:00:00Z',
                    updated_at: '2024-01-01T00:00:00Z',
                },
                created_at: '2024-01-01T00:00:00Z',
                updated_at: '2024-01-01T00:00:00Z',
            },
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
        },
        {
            id: 5,
            name: 'Packaging Line 1',
            description: 'Automated packaging line',
            cell_type: 'internal',
            has_finite_capacity: true,
            default_production_rate_per_hour: 50,
            default_unit_of_measure: 'units',
            default_setup_time_minutes: 20,
            max_parallel_executions: 1,
            is_active: true,
            area_id: 5,
            area: {
                id: 5,
                name: 'Packaging Area',
                description: 'Packaging and shipping preparation',
                plant_id: 1,
                plant: {
                    id: 1,
                    name: 'Main Plant',
                    description: 'Main manufacturing facility',
                    address: '123 Industrial Ave',
                    created_at: '2024-01-01T00:00:00Z',
                    updated_at: '2024-01-01T00:00:00Z',
                },
                created_at: '2024-01-01T00:00:00Z',
                updated_at: '2024-01-01T00:00:00Z',
            },
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
        },
    ] as any;

    // Dummy manufacturing orders - with dates that ensure visibility
    const orders = [
        {
            id: 1,
            order_number: 'MO-2024-001',
            status: 'in_progress',
            priority: 3, // High priority
            quantity: 100,
            quantity_completed: 30,
            quantity_scrapped: 0,
            unit_of_measure: 'units',
            requested_date: nextWeek.toISOString(),
            planned_start_date: twoDaysAgo.toISOString(),  // Started 2 days ago
            planned_end_date: threeDaysFromNow.toISOString(), // Ends in 3 days
            actual_start_date: twoDaysAgo.toISOString(),
            actual_end_date: undefined,
            item_id: 1,
            item: {
                id: 1,
                name: 'Widget Assembly A',
                code: 'WGT-001',
                item_number: 'WGT-001',
                description: 'Standard widget assembly',
                can_be_sold: true,
                can_be_purchased: false,
                can_be_manufactured: true,
                is_phantom: false,
                is_active: true,
                status: 'active',
                unit_of_measure: 'units',
                manufacturing_lead_time_days: 3,
                purchase_lead_time_days: 0,
                created_at: '2024-01-01T00:00:00Z',
                updated_at: '2024-01-01T00:00:00Z',
            },
            child_orders_count: 0,
            completed_child_orders_count: 0,
            auto_complete_on_children: false,
            has_route: true,
            progress_percentage: 30,
            quantity_remaining: 70,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
        },
        {
            id: 2,
            order_number: 'MO-2024-002',
            status: 'planned',
            priority: 2, // Medium priority
            quantity: 50,
            quantity_completed: 0,
            quantity_scrapped: 0,
            unit_of_measure: 'units',
            requested_date: addDays(today, 10).toISOString(),
            planned_start_date: addDays(today, 2).toISOString(),
            planned_end_date: addDays(today, 5).toISOString(),
            actual_start_date: undefined,
            actual_end_date: undefined,
            item_id: 2,
            item: {
                id: 2,
                name: 'Gear Box Model B',
                code: 'GBX-002',
                item_number: 'GBX-002',
                description: 'Heavy-duty gear box',
                can_be_sold: true,
                can_be_purchased: false,
                can_be_manufactured: true,
                is_phantom: false,
                is_active: true,
                status: 'active',
                unit_of_measure: 'units',
                manufacturing_lead_time_days: 5,
                purchase_lead_time_days: 0,
                created_at: '2024-01-01T00:00:00Z',
                updated_at: '2024-01-01T00:00:00Z',
            },
            child_orders_count: 0,
            completed_child_orders_count: 0,
            auto_complete_on_children: false,
            has_route: true,
            progress_percentage: 0,
            quantity_remaining: 50,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
        },
        {
            id: 3,
            order_number: 'MO-2024-003',
            status: 'planned',
            priority: 4, // Urgent priority
            quantity: 25,
            quantity_completed: 0,
            quantity_scrapped: 0,
            unit_of_measure: 'units',
            requested_date: addDays(today, 3).toISOString(),
            planned_start_date: tomorrow.toISOString(),
            planned_end_date: addDays(today, 2).toISOString(),
            actual_start_date: undefined,
            actual_end_date: undefined,
            item_id: 3,
            item: {
                id: 3,
                name: 'Control Panel Type C',
                code: 'CTL-003',
                item_number: 'CTL-003',
                description: 'Industrial control panel',
                can_be_sold: true,
                can_be_purchased: false,
                can_be_manufactured: true,
                is_phantom: false,
                is_active: true,
                status: 'active',
                unit_of_measure: 'units',
                manufacturing_lead_time_days: 2,
                purchase_lead_time_days: 0,
                created_at: '2024-01-01T00:00:00Z',
                updated_at: '2024-01-01T00:00:00Z',
            },
            child_orders_count: 0,
            completed_child_orders_count: 0,
            auto_complete_on_children: false,
            has_route: true,
            progress_percentage: 0,
            quantity_remaining: 25,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
        },
        // Add more visible orders
        {
            id: 4,
            order_number: 'MO-2024-004',
            status: 'in_progress',
            priority: 2, // Medium priority
            quantity: 75,
            quantity_completed: 45,
            quantity_scrapped: 0,
            unit_of_measure: 'units',
            requested_date: addDays(today, 5).toISOString(),
            planned_start_date: yesterday.toISOString(),
            planned_end_date: addDays(today, 2).toISOString(),
            actual_start_date: yesterday.toISOString(),
            actual_end_date: undefined,
            item_id: 4,
            item: {
                id: 4,
                name: 'Hydraulic Pump Assembly',
                code: 'HYD-004',
                item_number: 'HYD-004',
                description: 'Industrial hydraulic pump',
                can_be_sold: true,
                can_be_purchased: false,
                can_be_manufactured: true,
                is_phantom: false,
                is_active: true,
                status: 'active',
                unit_of_measure: 'units',
                manufacturing_lead_time_days: 3,
                purchase_lead_time_days: 0,
                created_at: '2024-01-01T00:00:00Z',
                updated_at: '2024-01-01T00:00:00Z',
            },
            child_orders_count: 0,
            completed_child_orders_count: 0,
            auto_complete_on_children: false,
            has_route: true,
            progress_percentage: 60,
            quantity_remaining: 30,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
        },
        {
            id: 5,
            order_number: 'MO-2024-005',
            status: 'in_progress',
            priority: 4, // Urgent
            quantity: 200,
            quantity_completed: 150,
            quantity_scrapped: 0,
            unit_of_measure: 'units',
            requested_date: tomorrow.toISOString(),
            planned_start_date: addDays(today, -3).toISOString(),
            planned_end_date: tomorrow.toISOString(),
            actual_start_date: addDays(today, -3).toISOString(),
            actual_end_date: undefined,
            item_id: 5,
            item: {
                id: 5,
                name: 'Electronic Control Module',
                code: 'ECM-005',
                item_number: 'ECM-005',
                description: 'Programmable control module',
                can_be_sold: true,
                can_be_purchased: false,
                can_be_manufactured: true,
                is_phantom: false,
                is_active: true,
                status: 'active',
                unit_of_measure: 'units',
                manufacturing_lead_time_days: 4,
                purchase_lead_time_days: 0,
                created_at: '2024-01-01T00:00:00Z',
                updated_at: '2024-01-01T00:00:00Z',
            },
            child_orders_count: 0,
            completed_child_orders_count: 0,
            auto_complete_on_children: false,
            has_route: true,
            progress_percentage: 75,
            quantity_remaining: 50,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
        },
    ] as any;

    // Dummy schedules with manufacturing steps
    const schedules = [
        // Order 1 - Widget Assembly A (spans from 2 days ago to 3 days from now)
        {
            id: 1,
            manufacturing_step_id: 1,
            work_cell_id: 1,
            scheduled_start: twoDaysAgo.toISOString(),
            scheduled_end: addHours(twoDaysAgo, 8).toISOString(),
            status: 'in_progress',
            is_locked: false,
            locked_by: undefined,
            locked_at: undefined,
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 1,
                name: 'Machining Components',
                description: 'Machine raw materials to specifications',
                status: 'in_progress',
                setup_time_minutes: 30,
                cycle_time_minutes: 240,
                manufacturing_route: {
                    id: 1,
                    manufacturing_order_id: 1,
                    manufacturing_order: {
                        id: 1,
                        order_number: 'MO-2024-001',
                        quantity: 100,
                        status: 'in_progress',
                        priority: 3,
                        requested_date: nextWeek.toISOString(),
                        item: {
                            id: 1,
                            name: 'Widget Assembly A',
                            item_number: 'WGT-001',
                        },
                    },
                },
            },
        },
        {
            id: 2,
            manufacturing_step_id: 2,
            work_cell_id: 2,
            scheduled_start: addHours(twoDaysAgo, 8).toISOString(),
            scheduled_end: yesterday.toISOString(),
            status: 'planned',
            is_locked: false,
            locked_by: undefined,
            locked_at: undefined,
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 2,
                name: 'Assembly',
                description: 'Assemble machined components',
                status: 'pending',
                setup_time_minutes: 15,
                cycle_time_minutes: 240,
                manufacturing_route: {
                    id: 1,
                    manufacturing_order_id: 1,
                    manufacturing_order: {
                        id: 1,
                        order_number: 'MO-2024-001',
                        quantity: 100,
                        status: 'in_progress',
                        priority: 3,
                        requested_date: nextWeek.toISOString(),
                        item: {
                            id: 1,
                            name: 'Widget Assembly A',
                            item_number: 'WGT-001',
                        },
                    },
                },
                dependency: {
                    id: 1,
                    name: 'Machining Components',
                },
            },
        },
        {
            id: 3,
            manufacturing_step_id: 3,
            work_cell_id: 4,
            scheduled_start: yesterday.toISOString(),
            scheduled_end: addHours(today, 4).toISOString(),
            status: 'planned',
            is_locked: false,
            locked_by: undefined,
            locked_at: undefined,
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 3,
                name: 'Quality Control',
                description: 'Inspect and test assembled units',
                status: 'pending',
                setup_time_minutes: 10,
                cycle_time_minutes: 120,
                manufacturing_route: {
                    id: 1,
                    manufacturing_order_id: 1,
                    manufacturing_order: {
                        id: 1,
                        order_number: 'MO-2024-001',
                        quantity: 100,
                        status: 'in_progress',
                        priority: 3,
                        requested_date: nextWeek.toISOString(),
                        item: {
                            id: 1,
                            name: 'Widget Assembly A',
                            item_number: 'WGT-001',
                        },
                    },
                },
                dependency: {
                    id: 2,
                    name: 'Assembly',
                },
            },
        },
        {
            id: 4,
            manufacturing_step_id: 4,
            work_cell_id: 5,
            scheduled_start: addHours(today, 4).toISOString(),
            scheduled_end: tomorrow.toISOString(),
            status: 'planned',
            is_locked: false,
            locked_by: undefined,
            locked_at: undefined,
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 4,
                name: 'Packaging',
                description: 'Package finished products for shipping',
                status: 'pending',
                setup_time_minutes: 20,
                cycle_time_minutes: 120,
                manufacturing_route: {
                    id: 1,
                    manufacturing_order_id: 1,
                    manufacturing_order: {
                        id: 1,
                        order_number: 'MO-2024-001',
                        quantity: 100,
                        status: 'in_progress',
                        priority: 3,
                        requested_date: nextWeek.toISOString(),
                        item: {
                            id: 1,
                            name: 'Widget Assembly A',
                            item_number: 'WGT-001',
                        },
                    },
                },
                dependency: {
                    id: 3,
                    name: 'Quality Control',
                },
            },
        },
        // Order 2 - Gear Box Model B
        {
            id: 5,
            manufacturing_step_id: 5,
            work_cell_id: 1,
            scheduled_start: addDays(today, 2).toISOString(),
            scheduled_end: addHours(addDays(today, 2), 6).toISOString(),
            status: 'planned',
            is_locked: false,
            locked_by: undefined,
            locked_at: undefined,
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 5,
                name: 'Machine Gear Components',
                description: 'Precision machining of gear components',
                status: 'pending',
                setup_time_minutes: 45,
                cycle_time_minutes: 360,
                manufacturing_route: {
                    id: 2,
                    manufacturing_order_id: 2,
                    manufacturing_order: {
                        id: 2,
                        order_number: 'MO-2024-002',
                        quantity: 50,
                        status: 'planned',
                        priority: 2,
                        requested_date: addDays(today, 10).toISOString(),
                        item: {
                            id: 2,
                            name: 'Gear Box Model B',
                            item_number: 'GBX-002',
                        },
                    },
                },
            },
        },
        {
            id: 6,
            manufacturing_step_id: 6,
            work_cell_id: 3,
            scheduled_start: addHours(addDays(today, 2), 6).toISOString(),
            scheduled_end: addHours(addDays(today, 2), 10).toISOString(),
            status: 'planned',
            is_locked: false,
            locked_by: undefined,
            locked_at: undefined,
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 6,
                name: 'Welding',
                description: 'Weld gear box housing',
                status: 'pending',
                setup_time_minutes: 30,
                cycle_time_minutes: 240,
                manufacturing_route: {
                    id: 2,
                    manufacturing_order_id: 2,
                    manufacturing_order: {
                        id: 2,
                        order_number: 'MO-2024-002',
                        quantity: 50,
                        status: 'planned',
                        priority: 2,
                        requested_date: addDays(today, 10).toISOString(),
                        item: {
                            id: 2,
                            name: 'Gear Box Model B',
                            item_number: 'GBX-002',
                        },
                    },
                },
                dependency: {
                    id: 5,
                    name: 'Machine Gear Components',
                },
            },
        },
        // Order 3 - Control Panel Type C
        {
            id: 7,
            manufacturing_step_id: 7,
            work_cell_id: 2,
            scheduled_start: tomorrow.toISOString(),
            scheduled_end: addHours(tomorrow, 3).toISOString(),
            status: 'planned',
            is_locked: true,
            locked_by: 1,
            locked_at: today.toISOString(),
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 7,
                name: 'Panel Assembly',
                description: 'Assemble control panel components',
                status: 'pending',
                setup_time_minutes: 15,
                cycle_time_minutes: 180,
                manufacturing_route: {
                    id: 3,
                    manufacturing_order_id: 3,
                    manufacturing_order: {
                        id: 3,
                        order_number: 'MO-2024-003',
                        quantity: 25,
                        status: 'planned',
                        priority: 4,
                        requested_date: addDays(today, 3).toISOString(),
                        item: {
                            id: 3,
                            name: 'Control Panel Type C',
                            item_number: 'CTL-003',
                        },
                    },
                },
            },
            locked_by_user: {
                id: 1,
                name: 'System Scheduler',
            },
        },
        {
            id: 8,
            manufacturing_step_id: 8,
            work_cell_id: 4,
            scheduled_start: addHours(tomorrow, 3).toISOString(),
            scheduled_end: addHours(tomorrow, 5).toISOString(),
            status: 'planned',
            is_locked: true,
            locked_by: 1,
            locked_at: today.toISOString(),
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 8,
                name: 'Electrical Testing',
                description: 'Test electrical connections and functionality',
                status: 'pending',
                setup_time_minutes: 10,
                cycle_time_minutes: 120,
                manufacturing_route: {
                    id: 3,
                    manufacturing_order_id: 3,
                    manufacturing_order: {
                        id: 3,
                        order_number: 'MO-2024-003',
                        quantity: 25,
                        status: 'planned',
                        priority: 4,
                        requested_date: addDays(today, 3).toISOString(),
                        item: {
                            id: 3,
                            name: 'Control Panel Type C',
                            item_number: 'CTL-003',
                        },
                    },
                },
                dependency: {
                    id: 7,
                    name: 'Panel Assembly',
                },
            },
            locked_by_user: {
                id: 1,
                name: 'System Scheduler',
            },
        },
        // Order 4 - Hydraulic Pump Assembly
        {
            id: 9,
            manufacturing_step_id: 9,
            work_cell_id: 1,
            scheduled_start: yesterday.toISOString(),
            scheduled_end: addHours(yesterday, 6).toISOString(),
            status: 'completed',
            is_locked: false,
            locked_by: undefined,
            locked_at: undefined,
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 9,
                name: 'Machine Pump Components',
                description: 'Machine hydraulic pump parts',
                status: 'completed',
                setup_time_minutes: 40,
                cycle_time_minutes: 360,
                manufacturing_route: {
                    id: 4,
                    manufacturing_order_id: 4,
                    manufacturing_order: {
                        id: 4,
                        order_number: 'MO-2024-004',
                        quantity: 75,
                        status: 'in_progress',
                        priority: 2,
                        requested_date: addDays(today, 5).toISOString(),
                        item: {
                            id: 4,
                            name: 'Hydraulic Pump Assembly',
                            item_number: 'HYD-004',
                        },
                    },
                },
            },
        },
        {
            id: 10,
            manufacturing_step_id: 10,
            work_cell_id: 2,
            scheduled_start: addHours(yesterday, 6).toISOString(),
            scheduled_end: today.toISOString(),
            status: 'in_progress',
            is_locked: false,
            locked_by: undefined,
            locked_at: undefined,
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 10,
                name: 'Pump Assembly',
                description: 'Assemble hydraulic pump',
                status: 'in_progress',
                setup_time_minutes: 20,
                cycle_time_minutes: 240,
                manufacturing_route: {
                    id: 4,
                    manufacturing_order_id: 4,
                    manufacturing_order: {
                        id: 4,
                        order_number: 'MO-2024-004',
                        quantity: 75,
                        status: 'in_progress',
                        priority: 2,
                        requested_date: addDays(today, 5).toISOString(),
                        item: {
                            id: 4,
                            name: 'Hydraulic Pump Assembly',
                            item_number: 'HYD-004',
                        },
                    },
                },
            },
        },
        // Order 5 - Electronic Control Module
        {
            id: 11,
            manufacturing_step_id: 11,
            work_cell_id: 2,
            scheduled_start: addDays(today, -3).toISOString(),
            scheduled_end: addDays(today, -2).toISOString(),
            status: 'completed',
            is_locked: false,
            locked_by: undefined,
            locked_at: undefined,
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 11,
                name: 'PCB Assembly',
                description: 'Assemble electronic circuit boards',
                status: 'completed',
                setup_time_minutes: 30,
                cycle_time_minutes: 480,
                manufacturing_route: {
                    id: 5,
                    manufacturing_order_id: 5,
                    manufacturing_order: {
                        id: 5,
                        order_number: 'MO-2024-005',
                        quantity: 200,
                        status: 'in_progress',
                        priority: 4,
                        requested_date: tomorrow.toISOString(),
                        item: {
                            id: 5,
                            name: 'Electronic Control Module',
                            item_number: 'ECM-005',
                        },
                    },
                },
            },
        },
        {
            id: 12,
            manufacturing_step_id: 12,
            work_cell_id: 4,
            scheduled_start: addDays(today, -2).toISOString(),
            scheduled_end: yesterday.toISOString(),
            status: 'completed',
            is_locked: false,
            locked_by: undefined,
            locked_at: undefined,
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 12,
                name: 'Functional Testing',
                description: 'Test electronic modules',
                status: 'completed',
                setup_time_minutes: 15,
                cycle_time_minutes: 480,
                manufacturing_route: {
                    id: 5,
                    manufacturing_order_id: 5,
                    manufacturing_order: {
                        id: 5,
                        order_number: 'MO-2024-005',
                        quantity: 200,
                        status: 'in_progress',
                        priority: 4,
                        requested_date: tomorrow.toISOString(),
                        item: {
                            id: 5,
                            name: 'Electronic Control Module',
                            item_number: 'ECM-005',
                        },
                    },
                },
            },
        },
        {
            id: 13,
            manufacturing_step_id: 13,
            work_cell_id: 5,
            scheduled_start: yesterday.toISOString(),
            scheduled_end: tomorrow.toISOString(),
            status: 'in_progress',
            is_locked: false,
            locked_by: undefined,
            locked_at: undefined,
            schedule_version_id: 1,
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            manufacturing_step: {
                id: 13,
                name: 'Final Packaging',
                description: 'Package control modules for shipping',
                status: 'in_progress',
                setup_time_minutes: 25,
                cycle_time_minutes: 960,
                manufacturing_route: {
                    id: 5,
                    manufacturing_order_id: 5,
                    manufacturing_order: {
                        id: 5,
                        order_number: 'MO-2024-005',
                        quantity: 200,
                        status: 'in_progress',
                        priority: 4,
                        requested_date: tomorrow.toISOString(),
                        item: {
                            id: 5,
                            name: 'Electronic Control Module',
                            item_number: 'ECM-005',
                        },
                    },
                },
            },
        },
    ] as any;

    // Dummy alerts
    const alerts = [
        {
            id: 1,
            schedule_version_id: 1,
            alert_type: 'capacity_overrun',
            severity: 'warning',
            message: 'Work cell CNC-001 is scheduled at 95% capacity on day 3',
            resolved: false,
            work_cell_id: 1,
            created_at: today.toISOString(),
            work_cell: {
                id: 1,
                name: 'CNC Machine 1',
            },
        },
        {
            id: 2,
            schedule_version_id: 1,
            alert_type: 'late_delivery',
            severity: 'error',
            message: 'Order MO-2024-003 is at risk of late delivery',
            resolved: false,
            manufacturing_order_id: 3,
            created_at: today.toISOString(),
            manufacturing_order: {
                id: 3,
                order_number: 'MO-2024-003',
            },
        },
        {
            id: 3,
            schedule_version_id: 1,
            alert_type: 'dependency_violation',
            severity: 'warning',
            message: 'Step dependency conflict detected for Order MO-2024-002',
            resolved: true,
            manufacturing_order_id: 2,
            manufacturing_step_id: 6,
            created_at: today.toISOString(),
            manufacturing_order: {
                id: 2,
                order_number: 'MO-2024-002',
            },
            manufacturing_step: {
                id: 6,
                name: 'Welding',
            },
        },
    ] as any;

    // Alert statistics
    const alertStats = {
        total: 3,
        unresolved: 2,
        by_type: {
            capacity_overrun: 1,
            dependency_violation: 1,
            late_delivery: 1,
        },
        by_severity: {
            error: 1,
            warning: 2,
        },
    };

    // Schedule versions
    const currentVersion = {
        id: 1,
        version_number: 1,
        status: 'draft',
        created_by: 1,
        published_by: undefined,
        published_at: undefined,
        last_algorithm_used: 'forward',
        last_scheduled_at: today.toISOString(),
        scheduling_status: 'completed',
        created_at: today.toISOString(),
        updated_at: today.toISOString(),
    } as any;

    const publishedVersion = {
        id: 0,
        version_number: 0,
        status: 'published',
        created_by: 1,
        published_by: 1,
        published_at: addDays(today, -7).toISOString(),
        last_algorithm_used: 'forward',
        last_scheduled_at: addDays(today, -7).toISOString(),
        scheduling_status: 'completed',
        created_at: addDays(today, -10).toISOString(),
        updated_at: addDays(today, -7).toISOString(),
    } as any;

    // Filters - Make sure the date range includes our dummy data
    const filters = {
        start_date: addDays(today, -7).toISOString(), // Start from a week ago
        end_date: addDays(today, 14).toISOString(),   // End two weeks from now
        search: '',
    };

    // Scheduling algorithms
    const schedulingAlgorithms = {
        forward: 'Forward Scheduling',
        backward: 'Backward Scheduling',
        capacity: 'Capacity-Based Scheduling',
        jit: 'Just-In-Time Scheduling',
    };

    return {
        currentVersion,
        publishedVersion,
        orders,
        schedules,
        alerts,
        alertStats,
        workCells,
        filters,
        schedulingAlgorithms,
    };
}